name       : wesnoth
version    : 1.13.7
release    : 4
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.13.7.tar.gz : 381149ea9be18d1ea0cbc6b9f469f02847f6faf63a884fd3f009cd5ba1dc828b
license    : GPL-2.0
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    A turn-based strategy game on a fantasy world
builddeps  :
    - libboost-devel
    - pkgconfig(cairo)
    - pkgconfig(fribidi)
    - pkgconfig(lua-5.1)
    - pkgconfig(pangocairo)
    - pkgconfig(python2)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/wesnothd.service $installdir/%libdir%/systemd/system/wesnothd.service
    install -m00644 -D $pkgfiles/wesnothd.tmpfiles $installdir/%libdir%/tmpfiles.d/wesnothd.conf
    rm -rf $installdir/var
