name       : wesnoth
version    : 1.13.10
release    : 8
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.13.10.tar.gz : 8617cdb2a7bb474ad041bc53748b96c98c37ecf0254f8c00ceced7f0d18c0fe0
license    : GPL-2.0
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    The Battle for Wesnoth is a Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat. Fight a desperate battle to reclaim the throne of Wesnoth, or take hand in any number of other adventures.
builddeps  :
    - libboost-devel
    - pkgconfig(cairo)
    - pkgconfig(fribidi)
    - pkgconfig(lua-5.1)
    - pkgconfig(pangocairo)
    - pkgconfig(python2)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(vorbis)
setup      : |
    %cmake . -DCMAKE_BUILD_TYPE=Release -DENABLE_OMP=ON -DMANDIR=/usr/share/man
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/wesnothd.service $installdir/%libdir%/systemd/system/wesnothd.service
    install -m00644 -D $pkgfiles/wesnothd.tmpfiles $installdir/%libdir%/tmpfiles.d/wesnothd.conf
    rm -rf $installdir/var
