name       : wesnoth
version    : 1.14.9
release    : 19
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.14.9.tar.gz : d2b700dea62c5727b792e70dc07a93f56fee35ac842dc506b9f22d9af4603f1f
license    : GPL-2.0-or-later
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    The Battle for Wesnoth is a Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat. Fight a desperate battle to reclaim the throne of Wesnoth, or take hand in any number of other adventures.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(fribidi)
    - pkgconfig(lua)
    - pkgconfig(pangocairo)
    - pkgconfig(vorbis)
    - libboost-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_OMP=ON -DMANDIR=/usr/share/man
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m00644 $pkgfiles/wesnothd.service $installdir/%libdir%/systemd/system/wesnothd.service
    install -D -m00644 $pkgfiles/wesnothd.tmpfiles $installdir/%libdir%/tmpfiles.d/wesnothd.conf
    rm -rf $installdir/var
