name       : wesnoth
version    : 1.14.7
release    : 15
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.14.7.tar.gz : e5e8acb36a48416cd76234a4b31cb15d929b882fe46f31c2239d1885432bf91a
license    : GPL-2.0-or-later
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    The Battle for Wesnoth is a Free, turn-based tactical strategy game with a high fantasy theme, featuring both single-player, and online/hotseat multiplayer combat. Fight a desperate battle to reclaim the throne of Wesnoth, or take hand in any number of other adventures.
builddeps  :
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(SDL2_net)
    - pkgconfig(SDL2_ttf)
    - pkgconfig(fribidi)
    - pkgconfig(lua)
    - pkgconfig(pangocairo)
    - pkgconfig(vorbis)
    - libboost-devel
setup      : |
    %cmake_ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_OMP=ON -DMANDIR=/usr/share/man
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -D -m00644 $pkgfiles/wesnothd.service $installdir/%libdir%/systemd/system/wesnothd.service
    install -D -m00644 $pkgfiles/wesnothd.tmpfiles $installdir/%libdir%/tmpfiles.d/wesnothd.conf
    rm -rf $installdir/var
