name       : wesnoth
version    : 1.12.6
release    : 2
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.12.6.tar.gz : cb80b089a06710bdb109ddfaa5ff83fe1598540be86035e80f8d16413cb54a59
license    : GPL-2.0
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    A turn-based strategy game on a fantasy world
builddeps  :
    - libboost-devel
    - pkgconfig(cairo)
    - pkgconfig(fribidi)
    - pkgconfig(lua-5.1)
    - pkgconfig(pangocairo)
    - pkgconfig(python2)
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_ttf)
    - pkgconfig(vorbis)
    - cmake
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/wesnothd.service $installdir/%libdir%/systemd/system/wesnothd.service
    install -m00644 -D $pkgfiles/wesnothd.tmpfiles $installdir/%libdir%/tmpfiles.d/wesnothd.conf
    rm -rf $installdir/var
