name       : wesnoth
version    : 1.12.6
release    : 1
source     :
    - https://github.com/wesnoth/wesnoth/archive/1.12.6.tar.gz : cb80b089a06710bdb109ddfaa5ff83fe1598540be86035e80f8d16413cb54a59
license    : GPL-2.0
component  : games.strategy
summary    : A turn-based strategy game on a fantasy world
description: |
    A turn-based strategy game on a fantasy world
builddeps  :
    - libboost-devel
    - lua
    - pkgconfig(cairo)
    - pkgconfig(pangocairo)
    - pkgconfig(fribidi)
    - dbus
    - libvorbis-devel
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(SDL_mixer)
    - pkgconfig(SDL_net)
    - pkgconfig(SDL_ttf)
    - pkgconfig(python2)
    - cmake
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
